# Generated by Django 3.2.16 on 2023-02-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_follow_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
